const htmlColorNames = [ "AliceBlue", "AntiqueWhite", "Aqua", "Aquamarine", "Azure", "Beige", "Bisque", "Black", "BlanchedAlmond", "Blue", "BlueViolet", "Brown", "BurlyWood", "CadetBlue", "Chartreuse", "Chocolate", "Coral", "CornflowerBlue", "Cornsilk", "Crimson", "Cyan", "DarkBlue", "DarkCyan", "DarkGoldenRod", "DarkGray", "DarkGreen", "DarkKhaki", "DarkMagenta", "DarkOliveGreen", "DarkOrange", "DarkOrchid", "DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSlateBlue", "DarkSlateGray", "DarkTurquoise", "DarkViolet", "DeepPink", "DeepSkyBlue", "DimGray", "DodgerBlue", "FireBrick", "FloralWhite", "ForestGreen", "Fuchsia", "Gainsboro", "GhostWhite", "Gold", "GoldenRod", "Gray", "Green", "GreenYellow", "HoneyDew", "HotPink", "IndianRed", "Indigo", "Ivory", "Khaki", "Lavender", "LavenderBlush", "LawnGreen", "LemonChiffon", "LightBlue", "LightCoral", "LightCyan", "LightGoldenRodYellow", "LightGray", "LightGreen", "LightPink", "LightSalmon", "LightSeaGreen", "LightSkyBlue", "LightSlateGray", "LightSteelBlue", "LightYellow", "Lime", "LimeGreen", "Linen", "Magenta", "Maroon", "MediumAquaMarine", "MediumBlue", "MediumOrchid", "MediumPurple", "MediumSeaGreen", "MediumSlateBlue", "MediumSpringGreen", "MediumTurquoise", "MediumVioletRed", "MidnightBlue", "MintCream", "MistyRose", "Moccasin", "NavajoWhite", "Navy", "OldLace", "Olive", "OliveDrab", "Orange", "OrangeRed", "Orchid", "PaleGoldenRod", "PaleGreen", "PaleTurquoise", "PaleVioletRed", "PapayaWhip", "PeachPuff", "Peru", "Pink", "Plum", "PowderBlue", "Purple", "RebeccaPurple", "Red", "RosyBrown", "RoyalBlue", "SaddleBrown", "Salmon", "SandyBrown", "SeaGreen", "SeaShell", "Sienna", "Silver", "SkyBlue", "SlateBlue", "SlateGray", "Snow", "SpringGreen", "SteelBlue", "Tan", "Teal", "Thistle", "Tomato", "Turquoise", "Violet", "Wheat", "White", "WhiteSmoke", "Yellow", "YellowGreen" ]
const btn = document.getElementById("btn")
const color = document.querySelector(".color")
const footer = document.querySelectorAll("footer")
const author = document.querySelectorAll("footer a")

btn.addEventListener("click", function() {
    const randomNumber = getRandomNumber()
    const randomColor = htmlColorNames[randomNumber]
    document.body.style.backgroundColor = randomColor
    color.textContent = randomColor
    
    const complementaryColor = getComplementaryColor(randomColor)
    footer.forEach(foot => {
        foot.style.color = complementaryColor
    })
    author.forEach(a => {
        a.style.color = complementaryColor
    })
})

function getRandomNumber() {
    return Math.floor(Math.random() * htmlColorNames.length)
}

function getComplementaryColor(color) {
    switch(color) {
        case "AliceBlue":
            return "#0F0700";
        case "AntiqueWhite":
            return "#051428";
        case "Aqua":
            return "#FF0000";
        case "Aquamarine":
            return "#80002B";
        case "Azure":
            return "#0F0000";
        case "Beige":
            return "#0A0A23";
        case "Bisque":
            return "#001B3B";
        case "Black":
            return "#FFFFFF";
        case "BlanchedAlmond":
            return "#001432";
        case "Blue":
            return "#FFFF00";
        case "BlueViolet":
            return "#75D41D";
        case "Brown":
            return "#5AD5D5";
        case "BurlyWood":
            return "#214778";
        case "CadetBlue":
            return "#A0615F";
        case "Chartreuse":
            return "#8000FF";
        case "Chocolate":
            return "#2D96E1";
        case "Coral":
            return "#0080AF";
        case "CornflowerBlue":
            return "#9B6A12";
        case "Cornsilk":
            return "#000723";
        case "Crimson":
            return "#233BC3";
        case "Cyan":
            return "#FF0000";
        case "DarkBlue":
            return "#FFFF74";
        case "DarkCyan":
            return "#FFF7474";
        case "DarkGoldenRod":
            return "#4779F4";
        case "DarkGray":
            return "#565656";
        case "DarkGreen":
            return "#FF9BFF";
        case "DarkKhaki":
            return "#424894";
        case "DarkMagenta":
            return "#74FF74";
        case "DarkOliveGreen":
            return "#AA94D0";
        case "DarkOrange":
            return "#0073FF";
        case "DarkOrchid":
            return "#66CD33";
        case "DarkRed":
            return "#74FFFF";
        case "DarkSalmon":
            return "#166985";
        case "DarkSeaGreen":
            return "#704370";
        case "DarkSlateBlue":
            return "#B7C274";
        case "DarkSlateGray":
            return "#D0B0B0";
        case "DarkTurquoise":
            return "#FF312E";
        case "DarkViolet":
            return "#6BFF2C";
        case "DeepPink":
            return "#00EB6C";
        case "DeepSkyBlue":
            return "#FF4000";
        case "DimGray":
            return "#969696";
        case "DodgerBlue":
            return "#E16F00";
        case "FireBrick":
            return "#4DDDDD";
        case "FloralWhite":
            return "#00050F";
        case "ForestGreen":
            return "#DD74DD";
        case "Fuchsia":
            return "#10FF00";
        case "Gainsboro":
            return "#232323";
        case "GhostWhite":
            return "#070700";
        case "Gold":
            return "#0028FF";
        case "GoldenRod":
            return "#255ADF";
        case "Gray":
            return "#7F7F7F";
        case "Green":
            return "#FF7FFF";
        case "GreenYellow":
            return "#5200D0";
        case "HoneyDew":
            return "#0F000F";
        case "HotPink":
            return "#00964B";
        case "IndianRed":
            return "#32A3A3";
        case "Indigo":
            return "#B4FF7D";
        case "Ivory":
            return "#00000F";
        case "Khaki":
            return "#0F1973";
        case "Lavender":
            return "#191905";
        case "LavenderBlush":
            return "#000F0A";
        case "LawnGreen":
            return "#8303FF";
        case "LemonChiffon":
            return "#000532";
        case "LightBlue":
            return "#522719";
        case "LightCoral":
            return "#0F7F7F";
        case "LightCyan":
            return "#1F0000";
        case "LightGoldenRodYellow":
            return "#05052D";
        case "LightGray":
            return "#2C2C2C";
        case "LightGreen":
            return "#6F116F";
        case "LightPink":
            return "#00493E";
        case "LightSalmon":
            return "#005F85";
        case "LightSeaGreen":
            return "#DF4D55";
        case "LightSkyBlue":
            return "#783105";
        case "LightSlateGray":
            return "#887766";
        case "LightSteelBlue":
            return "#3F3B21";
        case "LightYellow":
            return "#00001F";
        case "Lime":
            return "#FF00FF";
        case "LimeGreen":
            return "#CD32CD";
        case "Linen":
            return "#050F19";
        case "Magenta":
            return "#00FF00";
        case "Maroon":
            return "#7FFFFF";
        case "MediumAquaMarine":
            return "#993255";
        case "MediumBlue":
            return "#FFFF32";
        case "MediumOrchid":
            return "#45AA2C";
        case "MediumPurple":
            return "#6C8F24";
        case "MediumSeaGreen":
            return "#C34C8E";
        case "MediumSlateBlue":
            return "#849711";
        case "MediumSpringGreen":
            return "#FF0565";
        case "MediumTurquoise":
            return "#B72E33";
        case "MediumVioletRed":
            return "#38EA7A";
        case "MidnightBlue":
            return "#E6E68F";
        case "MintCream":
            return "#0A0005";
        case "MistyRose":
            return "#001B1E";
        case "Moccasin":
            return "#001B4A";
        case "NavajoWhite":
            return "#002152";
        case "Navy":
            return "#FFFF7F";
        case "OldLace":
            return "#020A19";
        case "Olive":
            return "#7F7FFF";
        case "OliveDrab":
            return "#9471DC";
        case "Orange":
            return "#005AFF";
        case "OrangeRed":
            return "#00BAFF";
        case "Orchid":
            return "#258F29";
        case "PaleGoldenRod":
            return "#111755";
        case "PaleGreen":
            return "#670467";
        case "PaleTurquoise":
            return "#501111";
        case "PaleVioletRed":
            return "#248F6C";
        case "PapayaWhip":
            return "#00102A";
        case "PeachPuff":
            return "#002546";
        case "Peru":
            return "#327AC0";
        case "Pink":
            return "#003F34";
        case "Plum":
            return "#225F22";
        case "PowderBlue":
            return "#4F1F19";
        case "Purple":
            return "#7FFF7F";
        case "RebeccaPurple":
            return "#99CC66";
        case "Red":
            return "#00FFFF";
        case "RosyBrown":
            return "#437070";
        case "RoyalBlue":
            return "#BE691E";
        case "SaddleBrown":
            return "#74BAEC";
        case "Salmon":
            return "#057F8D";
        case "SandyBrown":
            return "#0B5B9F";
        case "SeaGreen":
            return "#D174A8";
        case "SeaShell":
            return "#000A11";
        case "Sienna":
            return "#5FADD2";
        case "Silver":
            return "#3F3F3F";
        case "SkyBlue":
            return "#783114";
        case "SlateBlue":
            return "#95A532";
        case "SlateGray":
            return "#8F7F6F";
        case "Snow":
            return "#000505";
        case "SpringGreen":
            return "#FF0080";
        case "SteelBlue":
            return "#B97D4B";
        case "Tan":
            return "#2B4B73";
        case "Teal":
            return "#FF7F7F";
        case "Thistle":
            return "#274027";
        case "Tomato":
            return "#009CB8";
        case "Turquoise":
            return "#BF1F2F";
        case "Violet":
            return "#117D11";
        case "Wheat":
            return "#0A014C";
        case "White":
            return "#000000";
        case "WhiteSmoke":
            return "#0A0A0A";
        case "Yellow":
            return "#0000FF";
        case "YellowGreen":
            return "#6532CD";
        default:
            return "black";
    }
}